### ISSUE TITLE
Cannot link Caregiver with Companion due to mcdm-core error.

### ISSUE THREAD

**Issue by BuzzerPop** [trioderegion/mcdm-core#6]
I for some reason cannot link the caregiver and companion. I keep getting this error in the console:
![image](https://github.com/trioderegion/mcdm-core/assets/54551510/86e998c8-5495-4590-9f88-bc4a710b7ead)

**Comment by trioderegion** [comment]
I am poking at this a bit and cannot reproduce on v11 dnd5e 2.3.1.

Few things to check, do you own both the caregiver and companion, and does the caregiver have the beastheart class item?

**Comment by BuzzerPop** [comment]
Already solved this myself, apologies for not closing it earlier!
